FROM golang:1.9.2

# required to be passed in
ARG APP_PATH

ARG INSTALL_PATH=/go
ARG SRC_PATH=$INSTALL_PATH/src
ARG SRC_MAIN_PATH=$SRC_PATH/main
ARG LOCAL_USER=go

# Create a directory where our app will be placed
RUN mkdir -p $SRC_MAIN_PATH

# Get all the code needed to run the app
COPY $APP_PATH/. $INSTALL_PATH

# Change directory so that our commands run inside this new directory
WORKDIR $SRC_MAIN_PATH

# Install global packages with local user
RUN useradd -ms /bin/bash $LOCAL_USER
USER $LOCAL_USER

RUN go-wrapper download
RUN go-wrapper install

CMD ["go-wrapper", "run"]
